"""add_agent_jobs

Revision ID: 57a3fd95c05c
Revises: eb6f333d9da8
Create Date: 2026-05-07 17:40:01.085214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a3fd95c05c'
down_revision: Union[str, Sequence[str], None] = 'eb6f333d9da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_params', sa.Text(), nullable=True),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('prospects_found', sa.Integer(), nullable=False),
    sa.Column('prospects_created', sa.Integer(), nullable=False),
    sa.Column('prospects_skipped', sa.Integer(), nullable=False),
    sa.Column('draft_subject', sa.String(length=300), nullable=True),
    sa.Column('draft_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('agent_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_jobs')
    # ### end Alembic commands ###
